### PR TITLE
Added an empty virtual destructor to the ConstraintVisitor class.

### PR DESCRIPTION
**Pull request by 0x4d52**

### CODE REVIEW

**Comment by tristanpenman** [comment]
Your JUCE integration would be a valuable contribution, by the way. Let me know if there is any way I can assist.

I haven't looked at JUCE closely enough to know if this is relevant, but I experienced similar pointer vs iterator challenges when working with an earlier version of RapidJson. The iterators provided by the library were just pointer typedefs, if I remember correctly.

Last time I checked, that old version of RapidJson was still be supported by the RapidJson adapter. So it may serve as an example of how to implement this without changes to JUCE.

**Comment by 0x4d52** [comment]
My JUCE implementation is done and is at the link above (rather than on github as it would involve importing the whole JUCE tree into valijson). It was pretty easy basing it on your json11 adapter, until I hit the issue of missing iterators for the JSON object type.

Yes, JUCE just returns pointers from its begin() and end() methods for containers to implement iterators.

**Comment by tristanpenman** [comment]
@0x4d52, I wanted to check whether you intended to create a PR for your JUCE request (and waiting for feedback from the JUCE developers before doing that). From a copyright and attribution point of view, it is better for it to come in as a PR. But I may be able to simply pull the code from your link above if you would like to see it merged sooner.

**Comment by 0x4d52** [comment]
I wasn't going to do a PR for this. In terms of copyright, the code is pretty much a copy/paste job converting your Json11 adapter, I'd say that the code for the JUCE adapter is still way more than 50% your code. In terms of integrating the JUCE adapter into valijson it should be possible to include only the juce_core module (which contains the `var` class). This module has a liberal license, all the other modules are dual GPL/commerical. 

I've added juce_core to my fork in the thirdparty directory, to show how it might look.

**Pull request merged**
