### PR TITLE
Constraint builder

### PR DESCRIPTION
**Pull request by jhjensen**
In addition to the ConstraintBuilder changes I bundled some other minor changes, in order of anticipated controversy, to make it easy to leave out anything you don't like.

### CODE REVIEW

**Comment by tristanpenman** [comment]
All merged at commit efa2aec, with some changes to make SchemaParser take ownership of a ConstraintBuilder pointer instead of holding a reference. This makes the pointer ownership issue a bit more consistent with the rest of the library.

However, I'm considering an alternative approach, which is to a pass the vector of string/ConstraintBuilder pairs to the populateSchema() function. This would have the advantages of lower overhead (since it can be passed by reference), no confusion around ownership, and it would make the SchemaParser class immutable once again. The disadvantage is that your code might end up with more 'plumbing'.

I'll be interested to get your thoughts on that idea.

**Comment by jhjensen** [comment]
It wouldn't make to much difference to me.  It seems a little like exposing implementation details to me.

Perhaps a better interface would be instead of registering constraints, make SchemaParser call a virtual function for extra constraints, Then I would subclass SchemaParser to add my constraints.

**Comment by tristanpenman** [comment]
I really like your virtual function idea. At this stage, I'm starting to think about how some of these design weaknesses could be improved in a Valijson 'version 2', along with full support for C++11. But if we can get the current version to work for use case, that will be a great outcome too.

**Comment by jhjensen** [comment]
I took a short try at doing the virtual parser, but ran into a problem that a virtual function can't be templated.  The only way I know around that would be to make the whole class templated by adapter type, rather than each individual function.  Does that sound good to you?

**Comment by tristanpenman** [comment]
Thanks for looking into it. Unfortunately, I've run into similar issues in the past. It relates to one of my original design goals for Valijson which was to avoid the overhead of virtual dispatch for parts of the code that would be executed most frequently. However, I'm keen to stick to that approach for now, if only because so much work has gone into making it correct.

**Comment by jhjensen** [comment]
At least for my use case, building the schema isn't a performance issue. The overhead of a virtual function call is pretty small unless it breaks inlining.  I suspect less than the find it is using to get the jsonpath constraint.  I won't pursue this any further unless I hear from you.

**Pull request merged**
