### PR TITLE
Add polymorphic constraints, so that external constraints can be written.

### PR DESCRIPTION
**Pull request by jhjensen**
I don't expect this to be merged because:

- It depends on c++11
- there may be a better way to do it.
- It could use more testing.
- you may not like it all.

But I would appreciate any feedback.

### CODE REVIEW

**Comment by tristanpenman** [comment]
Sorry I've been a little slow to get back to you on this PR.

Overall, the concept is interesting, but I would be keen to see an example of a real-world constraint that can be supported by this implementation that is not also supported JSON Schema in its current form. My motivation for this is to avoid weakening the JSON Schema spec. If this feature could be used to experiment with currently unsupported constraints, that would be great. But I'm hesitant to add any features that encourage use of non-conformant schemas.

Also, the hard C++11 requirement may not be an issue. There are already parser adapters in Valijson for C++11-only parser libraries, and the build system has been updated accordingly. And taking that thought a step further, I am considering making C++11 a formal requirement for Valijson.

**Comment by jhjensen** [comment]
The test case I provided has a constraint that we would like to use internally.  I wouldn't expect it to be added to valijson.  Is it possible to implement it in a different way, without modifying valijson? 

I am new to json-schema, so it is likely I am missing something here.

**Comment by tristanpenman** [comment]
If I am reading the code correctly, `PathConstraint` is checking that a given JSON path exists in the document. One way you could achieve this using JSON Schema is model that path in your schema, and use a combination of the 'properties' and 'required' constraints to ensure that all nodes in the path are present. If you need more flexibility (e.g. node X required only if node Y is present) then the 'required' constraint may not be enough, in which case combining schemas using 'anyOf', 'allOf' or 'oneOf' should allow you to represent your schema.

**Comment by jhjensen** [comment]
It is checking that the given path appended with target document data is
present.  can that be done?

**Comment by tristanpenman** [comment]
I have had a bit more time to look at this and have a better understanding of what you want to achieve. The detail that threw me was that you automatically append the name of the property containing the 'jsonpath' constraint to the JSON path itself - I hadn't noticed that at first.

Obviously, designing an extension to JSON Schema is out of scope for Valijson, but I would still like to make this kind of dynamic validation easier. This probably shouldn't be done as a modification to the core set of constraints (there have been enough bugs there, even without encouraging users to add code that may not have been as rigorously tested).

In a use case like yours, does it make sense to make this an application-level check (perhaps via callbacks), rather than embedding it in the JSON Schema?

**Comment by jhjensen** [comment]
To me it makes more sense to embed it in the schema.  Otherwise we will be traversing the tree twice, using very similar code for gathering the error context.

I would suggest that virtual functions *are* callbacks, with the advantage that they are guaranteed set when the object is constructed.

You will notice that I have pushed some more changes that I hope are not to much for you to swallow.

I don't know if you think that the AdapterPath is a useful addition.  If so I would suggest it could go in utils.

I discovered that getObject and getArray return a copy of the document.  It works, but I am concerned about performance when we start validating large documents.  It also reduces the utility of AdapterPath, because you can't get a reference inside the original document.

Maybe we could get on IM and have a quicker discussion?

**Comment by tristanpenman** [comment]
Although it is a bit slower, I would like to keep any discussion on Github for now, especially now that I have had a chance to think about the issue some more. And besides, it might be interesting to someone one day.

I’ve been tinkering with the `PolyConstraint` changes in my dev environment, and it seems to work quite nicely. I think we might as well merge that and see what happens with it, but what I would like to do is to break that off as a separate change-set so that the other changes can be discussed separately.

Overall, I'm keen to preserve C++03 compatibility. I'm leaning towards C++11 support being a potential 'v2' requirement, while retaining C++03 compatibility for a reasonably feature complete version of the library.

So here is what I had in mind for next steps:

**1. PolyConstraint**

A fresh PR with just the `PolyConstraint` class could be merged immediately. That would modify:

 - include/valijson/constraints/concrete_constraints.hpp
 - include/valijson/constraints/constraint_visitor.hpp

This wouldn’t include `ConstraintBuilder`, but it lays the groundwork.

**2. ConstraintBuilder**

It would be good to modify the `addConstraintBuilder` function in the `SchemaParser` class to be explicit about ownership of the `ConstraintBuilder` instance (rather than the ambiguity of a reference). This may need some more discussion.

One suggestion here (which is C++03 friendly) is that instead of returning a `unique_ptr`, the ‘make’ function could allow a `Schema *` and `const *Subschema` to provided as arguments and directly call `addConstraintToSubschema`.

**3. Other unique_ptr changes**

The `unique_ptr` versions of `addConstraintToSubschema` in include/valijson/schema.hpp, and addConstraint in include/valijson/subschema.hpp could be merged once guarded by an `#ifdef` to check for C++11 support.

**4. getArray and getObject**

The copying performed by `getArray` and `getObject` is probably not as bad as it looks - though I would welcome any testing that can quantify the impact. The way Valijson is implemented at the moment, the behaviour of `getObject` and `getArray` will be dependent on individual adapter implementations, via `getObjectOptional` and `getArrayOptional`. These functions in turn rely on the Array and Object classes (provided by those adapters) which hold references to the underlying document. This should mean that all that is copied is a light-weight wrapper around reference. I *suspect* - but have no evidence to back this up - that move semantics would be slightly faster.

**5. AdapterPath**

These files aren’t visible in this PR for some reason.

**6. asString changes**

I haven’t looked at these in much detail yet, but it would be much easier to do so in a separate PR (referencing related issue).

—

Ideally, these would be done as separate PRs so that the changes can be discussed and merged independently. And then we can close off this PR, which is getting a bit too large to review effectively.

**Comment by jhjensen** [comment]
I am not surprised you want changes to be split, but I needed to share the code to start the conversation.

##### 1. 

You were tinkering with this.  Were you going to put it in, or me?

##### 2. 

How would you indicate ownership of the ConstraintBuilder?  I would say unique_ptr, but c++11.

 The reason I put in the unique ptr is exception safety.  Other than that I have no problem passing a pointer.  perhaps the code should be #if c11 uniqueptr #else pointer.

Or boost shared pointer could be used.

##### 4.
I will keep an eye on performance.  Now that you can look at AdapterPath you will see how I used them.
There may well be a better way to do all this.

##### 5.
I pushed a fix.  I made a mistake, and ended up doing a push -f, so If you have pulled this, be aware.

##### 6.
I use prints for debugging extensively, and an 'asString' that throws for valid objects pretty much kills that.

**Comment by tristanpenman** [comment]
I'm very appreciative that you've developed these ideas as far as you have - I think it is safe to say that the library will be improved once we get it all merged. I'm not sure if it is an important detail to you, but merging a clean PR for each step is also a nice way to trace attribution in the future. And I'd certainly like to start a list of contributors after this!

I think we should focus on 1 and 2 right now, since that will get us to a point where we have some of the groundwork merged into the master branch. If you have time to create a pull request to add the PolyConstraint class, I should be able to merge that almost immediately.

I think that a change from unique_ptr to raw pointers is the way to go for 2. There are some other parts of Valijson's 'public' API that use raw pointers (so that boost can eventually be removed as a hard dependency).

**Comment by tristanpenman** [comment]
Just wanted to check in to see if this is still a feature that you would like to pursue. I have a bit of time over the next few days to catch up on work related to Valijson, and if you haven't started already, I'd be more than happy to do some work on parts 1 and 2, as discussed above.

**Comment by tristanpenman** [comment]
I'm going to close this PR for now, as it has been a quite a while since any progress has been made. I've been busy enough that Valijson is pretty much in maintenance-mode these days, but these changes could be introduced in the future as smaller PRs.

**Pull request closed without merging**
