### PR TITLE
Support dropbox/json11.

### PR DESCRIPTION
**Pull request by hotwatermorning**
Add dropbox/json11 files and add wrapper classes and functions to support the library.

### CODE REVIEW

**Comment by tristanpenman** [comment]
Thanks for the PR! I'm hoping to review this later in the week.

It may take a little while for me to merge it, due to some build issues. Valijson aims to be compatible with C++03. A C++11 JSON adapter is a great additional to the library, but before I merge it, I would like to update the automated builds on Travis CI so that both C++03 and C++11 builds are tested.

**Comment by hotwatermorning** [comment]
`Valijson aims to be compatible with C++03`
I understood. :-)

Valijson is simple and useful library, so I would be happy if I could use valijson with dropbox/json11.

I'm looking forward to your review.
Thanks.

**Comment by tristanpenman** [comment]
I have hacked together a quick solution for the build problem. Travis CI will now test both C++03 and C++11 for clang, but only C++03 for GCC. When C++11 is enabled the `VALIJSON_BUILD_CXX11_ADAPTERS` preprocessor definition will be set to 1.

The test suite could be updated to only include json11 when `VALIJSON_BUILD_CXX11_ADAPTERS` is set - for example:

    #ifdef VALIJSON_BUILD_CXX11_ADAPTERS
    #include <valijson/adapters/json11_adapter.hpp>
    #endif

Do you have time to update your branch with these changes?

Eventually I will move the build to Travis CI's new Docker-based build platform. Hopefully a later version of GCC will be available so that it can be used to compile C++11 adapters as well.

**Comment by hotwatermorning** [comment]
Thank you for reviewing!
I merged tristanpenman/valijson's master and upgraded test sources to use VALIJSON_BUILD_CXX11_ADAPTERS.
I also modified CMakeLists.txt to ignore json11 when VALIJSON_CXX11_ADAPTERS is disabled.

Please review again. Thanks.

**Comment by tristanpenman** [comment]
Merged into master. Thanks again for the PR.

**Pull request merged**
